[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault_q3 = "J8BRYS7j32PyLFJ2uEenv6FC2yEVJdC8ZuVNi5kdu8EF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
